// roleType: Protective,

const cards = [
  {
    role: "godfather",
    roleType: ["Deceptive", "Passive", "Protective"],
    ally: "mafia",
    actPhase: "night",
    Image: "",
    desciption: "A Godfather is a role that investigates as Innocent to Cops.",
    isFlipped: false,
    isDead: false,
    id: 0,
  },
  {
    role: "mafia",
    roleType: ["Unpowered"],
    ally: "mafia",
    actPhase: "night",
    Image: "",
    desciption:
      "A member of the Mafia who has no abilities beyond the regular Mafia factional abilities.",
    isFlipped: false,
    isDead: false,
    id: 1,
  },
  {
    role: "Roleblocker",
    roleType: ["Manipulative"],
    ally: "mafia",
    actPhase: "night",
    Image: "",
    desciption:
      "A Roleblocker chooses one player per Night to block from performing their night action.",
    isFlipped: false,
    isDead: false,
    id: 2,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 3,
  },
  {
    role: "cop",
    roleType: ["Investigative"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption:
      "A Cop is a role that has the ability to investigate players at Night to discern their alignment.",
    isFlipped: false,
    isDead: false,
    id: 4,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 5,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 6,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 7,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 8,
  },
  {
    role: "doctor",
    roleType: ["Protective"],
    ally: "town",
    actPhase: "night",
    Image: "",
    desciption: "A Doctor protects players from being killed overnight.",
    isFlipped: false,
    isDead: false,
    id: 9,
  },
];

export default cards;
